# @see http://dqn.sakusakutto.jp/2016/01/ansible-mysql57-setup.html
- name: MySQLのユーザを作る
  # 設定するホストの集合
  hosts: db
  # sudoでタスクを実行するか
  become: True
  vars:
    mysql_user: hoge
    mysql_password: 8Mv9TGtN$
    mysql_database: mysql
  # ホストで実行するタスク
  tasks:

  - name: copy mysql config file
    copy: src=files/my.cnf dest=/etc/my.cnf

  - name: restart MySQL
    service: name=mysqld state=restarted

  - name: rootの一時パスワードを取り出し
    script: save-mysql-tmp-password.sh creates=/root/.tmp.my.cnf

  - name: rootのパスワードを変更
    script: change-root-password.sh creates=/root/.my.cnf

  - name: create mysql hoge user
    mysql_user: name=hoge host={{ item }} password={{ mysql_password }} priv={{ mysql_database }}.*:ALL state=present
    with_items:
      - localhost
      - 127.0.0.1

